android/app/src/netmain/AndroidManifest.xml
fixing links with ton:// scheme opening only on transfer host since we only parse those links
=> fix: fixing links with ton:// scheme

app/Navigation.tsx, app/components/PriceComponent.tsx, app/fragments/wallet/WalletFragment.tsx, app/sync/PriceContext.tsx, app/sync/products/PriceProduct.ts
fixed Price component accepting amount in props and exported price to context
=> fix: Price Component

android/build.gradle, patches/react-native-inappbrowser-reborn+3.6.3.patch
remove QUERY_ALL_PACKAGES permission
=> Fix: add android inapp browser patch

app/components/ValueComponent.tsx, app/engine/sync/startJettonMasterSync.ts, app/fragments/AccountsFragment.tsx, app/fragments/secure/SimpleTransferFragment.tsx, app/fragments/wallet/products/JettonProduct.tsx, app/fragments/wallet/products/ProductsComponent.tsx, app/utils/withDecimals.spec.ts, app/utils/withDecimals.ts
Fixes:
- Corrected to and from BN with decimals operations
- Typo in JettonProduct component name
- ValueComponent decimals check
- SimpleTransfer fragment jettonMaster check
Added: 
- More test cases
=> Fixes for jetton's decimals support

app/fragments/AccountsFragment.tsx, app/fragments/wallet/products/JettonProduct.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts
https://user-images.githubusercontent.com/32094306/194541907-61ebc4e4-64d6-480e-8717-3d19ff2f41bb.MP4
=> add: adding confirmJettonAction on default onLongPress for jetton product view

app/components/WalletAddress.tsx, app/fragments/secure/MigrationFragment.tsx, app/fragments/staking/StakingFragment.tsx, app/fragments/wallet/ReceiveFragment.tsx, app/fragments/wallet/TransactionPreviewFragment.tsx, app/fragments/wallet/WalletFragment.tsx
Added monotype address, split into two rows, fixed layout
=> Fix: fixing WalletAddress component

app/fragments/staking/StakingTransferFragment.tsx
possible second withdraw request
=> improvement: adding additional withdrawFee subtraction

app/components/Avatar.tsx, app/engine/products/WalletProduct.ts, app/fragments/wallet/TransactionPreviewFragment.tsx, app/fragments/wallet/products/JettonProduct.tsx, app/fragments/wallet/products/ProductButton.tsx, app/fragments/wallet/views/TransactionView.tsx, app/secure/KnownWallets.ts
=> feat: adding verified known Jetton Masters

app/fragments/wallet/TransactionPreviewFragment.tsx, app/fragments/wallet/views/TransactionView.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts, app/i18n/schema.ts
Release Notes: Minor UI improvements
=> fix: transaction preview fragment layout

app/components/ValueComponent.tsx
=> fix: show only 2 last cents if balance.length > 2

app/components/Staking/StakingProductComponent.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts
=> fix: adding real APY for Staking Product

app/i18n/i18n_en.ts
=> fixed a typo

app/components/WalletAddress.tsx, app/fragments/wallet/TransactionPreviewFragment.tsx
=> fix: remove monospace font on wallet address

app/components/QRCode/QRCode.tsx, app/components/QRCode/QRMatrix.ts
=> ui: change qr-code generation

app/fragments/wallet/views/TransactionView.tsx
=> fix: android transaction view layout

app/fragments/wallet/products/ProductButton.tsx
=> fix: extensions product button layout

app/fragments/wallet/products/ProductsComponent.tsx
=> fix: separating staking from extensions on the main screen

app/fragments/secure/TransferFragment.tsx
Changed this to show recipients address instead of Jettons Wallet address
=> fix: changed displayed address on jetton transfer

app/components/CopyButton.tsx, app/components/ShareButton.tsx, app/fragments/wallet/ReceiveFragment.tsx
To account for unusual font sizes & translations texts
Before
After
=> fix: fix: share & copy buttons layout on Receive fragment 

app/Navigation.tsx, app/components/QRCode/QRCode.tsx, app/components/WImage.tsx, app/engine/products/WalletProduct.ts, app/fragments/HomeFragment.tsx, app/fragments/apps/components/AppComponent.tsx, app/fragments/apps/components/ConnectAppComponent.tsx, app/fragments/secure/SimpleTransferFragment.tsx, app/fragments/secure/TonConnectAuthenticateFragment.tsx, app/fragments/secure/TransferFragment.tsx, app/fragments/wallet/AssetsFragment.tsx, app/fragments/wallet/ReceiveFragment.tsx, app/fragments/wallet/WalletFragment.tsx, app/fragments/wallet/products/JettonProduct.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts, app/i18n/schema.ts, app/useLinkNavigator.ts, app/utils/resolveUrl.ts
With url param ?jetton=friendlyAddress
where jetton address is Jettons Master
https://user-images.githubusercontent.com/32094306/225936408-428554b3-f3c3-49df-be15-7654cbb19e81.MP4
https://user-images.githubusercontent.com/32094306/225936478-f3a7b355-080b-43ed-893e-314c14d2c31d.MP4
https://user-images.githubusercontent.com/32094306/226967936-ef99e616-5f39-4d5f-82ab-ab904bba4824.MP4
=> feat: adding jetton transfer link support

app/engine/Persistence.ts, app/engine/metadata/Metadata.ts, app/engine/metadata/introspections/tryFetchJettonMaster.spec.ts, app/engine/metadata/introspections/tryFetchJettonMaster.ts, app/engine/sync/startJettonMasterSync.ts, app/secure/KnownWallets.ts
=> fix/improvement: adding bridge tokens support & verification

app/fragments/connections/ConnectionsFragment.tsx, app/fragments/ledger/LedgerRoot.tsx, app/fragments/ledger/components/LedgerApp.tsx, app/fragments/ledger/components/LedgerBle.tsx, app/fragments/ledger/components/LedgerBleDescription.tsx, app/fragments/ledger/components/LedgerDeviceSelection.tsx, app/fragments/wallet/ReceiveFragment.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts, app/i18n/schema.ts
- adding android permissions requests layout
- fixing android toolbar position on ConnectionsFragment
- fixing ledger assets navigation
=> fix: android permissions, android toolbar position, ledger assets navigation

App.tsx, ios/Podfile.lock, package.json, yarn.lock
*also some chode auto updated libs
=> wip: fixing XCode cloud build with sentry

ios/Podfile.lock, package.json, patches/expo-secure-store+12.5.0.patch, yarn.lock
+ chore bump secure store version
=> fix: add secure-store device passcode access control

app/fragments/secure/SimpleTransferFragment.tsx
- invalid amount on empty input
- empty balance check
=> Fix: transfer hotfix

android/app/src/main/AndroidManifest.xml, app/fragments/onboarding/LegalFragment.tsx
- Adding android manifest conflicts resolution strategy
=> Develop to Master

app/fragments/ledger/LedgerSignTransferFragment.tsx, app/fragments/secure/components/TransferBatch.tsx, app/fragments/secure/components/TransferSingle.tsx
- fixing transfer cancel tracking
- fixing transfer batch tracking
- fixing Each child in a list should have a unique "key" prop error
=> fix: fixing transfer Mixpanel event tracking

app/fragments/wallet/AvatarPickerFragment.tsx, app/fragments/wallet/WalletSettingsFragment.tsx
=> fix: fixing Wallet settings and Avatar picker layouts and adding name trim

app/fragments/wallet/TransactionPreviewFragment.tsx, app/fragments/wallet/views/TransactionView.tsx
=> fix: fixing avatar hash for own wallets, name titles for txs views and preview

app/components/DappMainButton.tsx, app/components/toast/ToastProvider.tsx, app/components/webview/DAppWebView.tsx, app/components/webview/utils/extractWebViewQueryAPIParams.ts, app/components/webview/utils/isSafeDomain.ts, app/components/webview/utils/processStatusBarMessage.ts, app/fragments/apps/components/inject/createInjectSource.ts, app/fragments/apps/components/protect/protectNavigation.ts, app/fragments/holders/components/HoldersAppComponent.tsx
- fixing safe domain check
- fixing subscribed callback param returned
- fixing immutable objects in injected APIs
=> Develop into release/v2.0.1

app/components/DappMainButton.tsx, app/components/toast/ToastProvider.tsx, app/components/webview/DAppWebView.tsx, app/components/webview/utils/extractWebViewQueryAPIParams.ts, app/components/webview/utils/isSafeDomain.ts, app/components/webview/utils/processStatusBarMessage.ts, app/fragments/apps/components/inject/createInjectSource.ts, app/fragments/apps/components/protect/protectNavigation.ts, app/fragments/holders/components/HoldersAppComponent.tsx, app/fragments/secure/components/TransferBatch.tsx
- Critical batch transfer payload fix
- Fixed safety checks for dApp WebView inject APIs
=> Develop into release 2.0.1

app/fragments/wallet/products/DappsRequests.tsx, app/fragments/wallet/views/DappRequestButton.tsx, app/fragments/wallet/views/TonConnectRequestButton.tsx, app/fragments/wallet/views/TonXRequestButton.tsx
exported dapp request buttons to separate components to not to call ton-x metadata on ton-connect requests
=> fix: DApp requests button components

app/components/webview/DAppWebView.tsx, app/fragments/holders/HoldersAppFragment.tsx, app/fragments/holders/components/HoldersAppComponent.tsx, app/fragments/utils/DAppWebViewFragment.tsx
- fixed ios status bar on holders and dapp webview fragments
- fixed main-button position
prev: 
new:
=> fix: fixing status bar & main button position

app/fragments/secure/dapps/DappAuthComponent.tsx
=> fix: fixing dapp auth component with platform dependent styles

app/engine/transactions/parseMessageBody.ts, app/engine/transactions/parseWalletTransaction.ts, package.json, yarn.lock
- upgrading @ton/core lib
- adding isExotic cell checks for messages parsing
=> fix: fixing exotics

android/app/src/main/AndroidManifest.xml, app/fragments/ledger/components/TransportContext.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts, app/i18n/schema.ts
- [Android]: fixing manifest merge
- Adding bluetooth transport error typed alerts
=> fix: manifest permissions merge

android/app/src/main/AndroidManifest.xml, app/components/address/AddressInputAvatar.tsx, app/components/address/AddressSearch.tsx, app/components/address/AddressSearchItemView.tsx, app/components/address/TransferAddressInput.tsx, app/components/wallet/WalletItem.tsx, app/components/wallet/WalletSelector.tsx, app/fragments/ledger/LedgerHomeFragment.tsx, app/fragments/secure/components/TransferSingleView.tsx, app/fragments/secure/dapps/DappAuthComponent.tsx
- ledger android ble connection (manifest according to ([react-native-ble](https://github.com/dotintent/react-native-ble-plx)) and not ledger docs);
- adding ledger as searcheable in Address input;
- ledger receive address format;
- ledger transfer avatar, labeling;
- ledger address format on wallet selector
=> fix: Ledger related fixes in context of new address format

app/fragments/secure/dapps/DappAuthComponent.tsx
=> fix: fixing android layout

app/components/address/AddressSearch.tsx
=> fix: fixing ledger address display on address search

app/engine/hooks/dapps/useAutoConnect.ts, app/fragments/staking/LiquidStakingTransferFragment.tsx
fix init amount for liquid staking transferFragment
=> fix: useAutoConnect to handle missing app and connections &

app/components/products/HoldersAccountItem.tsx, app/components/products/HoldersCards.tsx, app/components/products/HoldersPrepaidCard.tsx
& prepaid cards price amount fix
=> fix: AccountItem and PrepaidCard components value re-rending

app/fragments/wallet/TransactionPreviewFragment.tsx, app/fragments/wallet/views/WalletTransactions.tsx
=> fix: fixing target address format

app/fragments/wallet/TransactionsFragment.tsx
=> fix: fixing pending txs on wallet transactions address

app/components/browser/BrowserSearch.tsx
& set autoCapitalize to 'none'
=> fix: Normalize URL in BrowserSearch component

app/Navigation.tsx, app/components/TonconnectWatcher.tsx, app/engine/hooks/dapps/useConnectPendingRequests.ts, app/engine/hooks/dapps/useHandleMessage.ts, app/engine/state/tonconnect.ts, app/engine/tonconnect/types.ts, app/engine/tonconnectWatcher.ts, app/fragments/HomeFragment.tsx, app/i18n/i18n_en.ts, app/i18n/i18n_ru.ts, app/i18n/schema.ts, app/useLinkNavigator.ts, app/utils/resolveUrl.ts
=>  feat/fix: tonconnect watcher & push tc request resolver

app/engine/hooks/jettons/useSpecialJetton.ts, app/fragments/wallet/JettonWalletFragment.tsx
(jetton wallet fragment related bugs)
=> fix: rate string & specialJetton wallet

app/fragments/holders/components/CardPlaceholder.tsx, app/fragments/holders/components/HoldersAppComponent.tsx
=> add: adding prepaid cards loader animation and buttons

app/fragments/HomeFragment.tsx, app/fragments/W5UpdateFragment.tsx, app/fragments/secure/TransferFragment.tsx, app/fragments/wallet/views/WalletTransactions.tsx
=> fix: add home tabs freeze, add renderItem useCallback, safety checks

app/components/products/JettonsProductComponent.tsx, app/components/products/ProductsComponent.tsx, app/components/products/SavingsProduct.tsx, app/engine/hooks/jettons/index.ts, app/engine/hooks/jettons/useDisplayableJettons.ts, app/fragments/wallet/JettonWalletFragment.tsx, app/secure/KnownWallets.ts
fix: fixing jetton wallet not navigating on some clicks
add: marking liquid staking tokens as verified
=> feat: filtering jettons list, adding some to savings and removing from a list

app/engine/hooks/dapps/useDAppBridge.ts, app/engine/hooks/dapps/useHoldersLedgerTonconnectHandler.ts, app/engine/hooks/transactions/usePeparedMessages.ts, app/fragments/ledger/LedgerSignTransferFragment.tsx, app/fragments/secure/components/TransferBatch.tsx, app/fragments/secure/components/TransferSingleView.tsx, app/fragments/secure/ops/Order.ts, app/utils/holders/validateLedgerJettonTransfer.ts
also fixing payload parsings + code cleanup
=> feat: adding a crutch to support ledger jetton transfer payload via tonconnect

android/app/src/main/java/com/tonhub/wallet/MainActivity.java, android/app/src/main/java/com/tonhub/wallet/MainApplication.java, android/app/src/main/java/com/tonhub/wallet/modules/flagsecure/FlagSecureModule.java, android/app/src/main/java/com/tonhub/wallet/modules/flagsecure/FlagSecurePackage.java, app/components/products/HoldersProductComponent.tsx, app/engine/hooks/index.ts, app/engine/hooks/useSecureScreen.ts, app/fragments/holders/HoldersAppFragment.tsx, app/modules/SecureScreen.ts, app/modules/nativeModules.d.ts
Стало:
https://github.com/user-attachments/assets/bd12a7c3-e7b6-4cf8-a87b-5627b345c863
=> feat: secure android screens

app/engine/state/theme.ts, app/fragments/ThemeFragment.tsx
https://github.com/user-attachments/assets/fedd2207-7255-49bc-a330-c0aaac5bd0e5
=> fix: change bottom bar color on changing theme

app/fragments/wallet/JettonWalletFragment.tsx, app/fragments/wallet/TonWalletFragment.tsx
https://github.com/user-attachments/assets/0553e98a-1175-4ab3-914d-5b6daa358859
=> fix: container styles in JettonWalletFragment and TonWalletFragment

app/fragments/wallet/TransactionPreviewFragment.tsx
=> fix: fix address format

app/components/Splash.tsx, app/engine/ThemeContext.tsx
https://github.com/user-attachments/assets/a907e0fc-df49-4fc8-aec4-1f6f6f309ad8
=> fix: android nav bar color

app/fragments/wallet/TransactionPreviewFragment.tsx
https://github.com/user-attachments/assets/0c240c02-d70b-462e-b455-0c7f303a0717
=> fix: avatar color in TransactionPreview

app/components/AppModeToggle.tsx, app/components/address/WalletAddress.tsx, app/components/products/LedgerProductsComponent.tsx, app/components/wallet/SelectedWallet.tsx, app/engine/hooks/appstate/useAppMode.ts, app/engine/hooks/wallet/useWalletCardLayoutHelper.ts, app/fragments/HomeFragment.tsx, app/fragments/SettingsFragment.tsx, app/fragments/ledger/LedgerAppFragment.tsx, app/fragments/ledger/LedgerHomeFragment.tsx, app/fragments/ledger/components/LedgerWalletHeader.tsx, app/fragments/wallet/ReceiveAssetsFragment.tsx, app/fragments/wallet/views/WalletActionButton.tsx, app/fragments/wallet/views/WalletActions.tsx, app/fragments/wallet/views/WalletCard.tsx, app/fragments/wallet/views/WalletHeader.tsx, app/i18n/i18n_de.ts, app/i18n/i18n_en.ts, app/i18n/i18n_es.ts, app/i18n/i18n_fr.ts, app/i18n/i18n_it.ts, app/i18n/i18n_pt.ts, app/i18n/i18n_ru.ts, app/i18n/i18n_uk.ts, app/i18n/schema.ts
=> feat: separation UI changes

app/components/animated/CollapsibleCards.tsx, app/components/products/HoldersAccounts.tsx
=> feat: holders accounts always expanded

app/fragments/wallet/JettonWalletFragment.tsx, app/fragments/wallet/TonWalletFragment.tsx, app/fragments/wallet/views/JettonWalletTransactions.tsx, app/fragments/wallet/views/WalletTransactions.tsx
Copied styling from SolanaWalletFragment
=> fix: transactions bottom padding

app/components/passcode/PasscodeInput.tsx, app/components/passcode/PasscodeKeyButton.tsx, app/components/passcode/PasscodeKeyboard.tsx, app/components/passcode/PasscodeStep.tsx, app/components/passcode/PasscodeSteps.tsx, app/components/products/StakingProductComponent.tsx, app/components/secure/AuthWalletKeys.tsx, app/fragments/AppAuthFragment.tsx
- reduce rerenders, improve performance
- disable buttons on loading
- pin steps become a loader on loading
- increase clickable area for PIN keyboard buttons
=> PIN code screen refactoring
